#!/usr/bin/env python3
"""Validate and import the NARRA canonical reference image (PHASE 1.1).

The reference is the source of truth for every derived asset, so it is checked
against ASSET_SPEC.md before it is allowed into character/reference/.

Usage:
    validate_reference.py <candidate.png>            validate only, write nothing
    validate_reference.py <candidate.png> --import   validate, then import on pass
    validate_reference.py --check-imported           re-validate what is already imported

Exit code 0 = all checks passed, 1 = at least one FAIL, 2 = usage error.

Pillow is used for pixel-level checks. Without it the script still runs and
performs header-level checks from the stdlib, and reports the pixel checks as
skipped rather than passed.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
import imagecheck                                            # noqa: E402
from imagecheck import FAIL, PASS, Report, sha256            # noqa: E402

# NARRA_REPO lets the test suite point the importer at a throwaway tree.
REPO = Path(os.environ.get("NARRA_REPO", Path(__file__).resolve().parents[2]))

CHARACTER = "narra"
VERSION = 1
REF_DIR = REPO / "character" / "reference"
MASTER = REF_DIR / f"{CHARACTER}-reference-master-v{VERSION}.png"
ALIAS = REF_DIR / "master.png"
SIDECAR = REF_DIR / f"{CHARACTER}-reference-master-v{VERSION}.json"
MIRROR = REPO / "metadata" / "generations" / f"{CHARACTER}-reference-master-v{VERSION}.json"

REQUIRED_SIZE = imagecheck.REQUIRED_SIZE


def visual_checklist():
    """Checks a script cannot make. Printed so they are not silently skipped."""
    return [
        "REST mouth - relaxed and closed; all 16 visemes are edits of this mouth",
        "Neutral expression, gaze at camera",
        "Head fully in frame; no crop of hair or chin",
        "Head angle is the one angle the whole library will use",
        "Clean alpha edge - no fringe from the generation background",
        "Art style matches the intended library style (character-bible.md section 9)",
    ]


def build_sidecar(path):
    """Reference metadata per ASSET_SPEC.md section 11.

    Generation fields are null: this file is imported, not generated by this
    pipeline. They are filled in if and when the reference is regenerated
    locally, at which point the reference becomes reproducible from metadata alone.
    """
    return {
        "character": CHARACTER,
        "asset_type": "reference",
        "asset_name": "master",
        "version": VERSION,
        "file": str(MASTER.relative_to(REPO)),
        "reference": None,
        "sha256": sha256(path),
        "model": {"name": None, "precision": None, "file": None},
        "workflow": {"file": None, "version": None},
        "prompt": {
            "master_version": None,
            "asset_prompt_version": None,
            "compiled": None,
            "negative": None,
        },
        "generation": {
            "seed": None,
            "steps": None,
            "cfg": None,
            "sampler": None,
            "scheduler": None,
            "denoise": None,
            "resolution": list(REQUIRED_SIZE),
        },
        "mouth_anchor": {
            "anchor_x": None,
            "anchor_y": None,
            "mouth_width": None,
            "mouth_height": None,
        },
        "environment": {"comfyui_version": "", "custom_nodes": []},
        "validation": {
            "status": "imported",
            "validated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "notes": "Automated checks in scripts/validation/validate_reference.py passed. "
                     "Visual checklist and PHASE 1.4 baseline tests still required before "
                     "status becomes approved.",
        },
        "generated_at": None,
    }


def do_import(path):
    REF_DIR.mkdir(parents=True, exist_ok=True)
    MIRROR.parent.mkdir(parents=True, exist_ok=True)

    data = path.read_bytes()
    MASTER.write_bytes(data)
    ALIAS.write_bytes(data)

    sidecar = json.dumps(build_sidecar(MASTER), indent=2) + "\n"
    SIDECAR.write_text(sidecar)
    MIRROR.write_text(sidecar)

    print("\nImported:")
    for target in (MASTER, ALIAS, SIDECAR, MIRROR):
        print(f"  {target.relative_to(REPO)}")


def check_imported(report):
    if not MASTER.exists():
        report.add(FAIL, "imported/master", f"{MASTER.relative_to(REPO)} not found - run --import")
        return False
    report.add(PASS, "imported/master", str(MASTER.relative_to(REPO)))

    if not ALIAS.exists():
        report.add(FAIL, "imported/alias", "master.png missing (see character/reference/README.md)")
    elif ALIAS.read_bytes() != MASTER.read_bytes():
        report.add(FAIL, "imported/alias",
                   "master.png is not byte-identical to the versioned master - "
                   "workflows and QC would disagree about what the reference is")
    else:
        report.add(PASS, "imported/alias", "master.png byte-identical to versioned master")

    for label, target in (("sidecar", SIDECAR), ("sidecar/mirror", MIRROR)):
        if not target.exists():
            report.add(FAIL, f"imported/{label}", f"{target.relative_to(REPO)} missing (ASSET_SPEC 11)")
            continue
        try:
            recorded = json.loads(target.read_text())
        except json.JSONDecodeError as exc:
            report.add(FAIL, f"imported/{label}", f"invalid JSON: {exc}")
            continue
        if recorded.get("sha256") != sha256(MASTER):
            report.add(FAIL, f"imported/{label}",
                       "sha256 does not match the master image - the reference changed "
                       "without being re-imported")
        else:
            report.add(PASS, f"imported/{label}", "present, sha256 matches")

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Validate and import the NARRA canonical reference image (PHASE 1.1).")
    parser.add_argument("candidate", nargs="?", type=Path,
                        help="candidate reference image to validate")
    parser.add_argument("--import", dest="do_import", action="store_true",
                        help="import the candidate if every check passes")
    parser.add_argument("--check-imported", action="store_true",
                        help="re-validate the already-imported reference")
    args = parser.parse_args()

    if not args.candidate and not args.check_imported:
        parser.error("give a candidate image, or --check-imported")
    if args.do_import and args.check_imported:
        parser.error("--import and --check-imported are separate operations")

    report = Report()
    target = args.candidate

    if args.check_imported:
        print(f"Checking imported reference in {REF_DIR.relative_to(REPO)}\n")
        if check_imported(report):
            target = MASTER
    else:
        if not target.exists():
            print(f"error: {target} not found", file=sys.stderr)
            return 2
        print(f"Validating {target}\n")

    if target and target.exists():
        if imagecheck.check_header(target, report):
            imagecheck.check_pixels(target, report)

    print(report.render())

    if report.failed():
        if args.check_imported:
            print("\nFAILED - the imported reference does not match ASSET_SPEC or its "
                  "recorded metadata.")
        else:
            print("\nFAILED - the candidate does not meet ASSET_SPEC. Not imported.")
        return 1

    print("\nAutomated checks passed.")
    print("\nStill to confirm by eye - a script cannot check these:")
    for item in visual_checklist():
        print(f"  [ ] {item}")

    if args.do_import:
        do_import(target)
        print("\nNext: fill character/bible/character-bible.md and visual-spec.md from this image.")
    elif not args.check_imported:
        print("\nRe-run with --import to write it into character/reference/.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
